config/routes.rb
 Studyvault::Application.routes.draw do
  
  root :to => "pages#index"
  
  resources :users do
    get 'add', :on => :member
  end
  
  resources :uploads, :only =>[:create, :destroy, :show]
  
  resources :uploads do
    get 'download', :on => :member
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :schools do
    resources :requests
  end
  
  resources :courses
  resources :comments
  
  resources :downloads
  
  resources :purchases
  
  resources :requests do
    resources :responses
  end
  
  resources :responses do
    get 'download', :on => :member
    get 'accept', :on => :member
  end
  
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'
  match '/about',     :to => 'pages#about'
  match '/aboutswag', :to => 'pages#aboutswag'
  match '/terms',     :to => 'pages#terms'
  match '/upload',    :to => 'pages#upload'
  match '/search',     :to => 'pages#search'
  
  match '/schoolsearch', :to => 'schools#search'
  match '/coursesearch', :to => 'courses#search'
  match '/professors',   :to => 'pages#professors'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope :order => 'users.id ASC'
  
  attr_accessor :password
  attr_accessible :username, :email, :password, 
                  :password_confirmation, :confirmed, 
                  :school_id, :graduation, 
                  :admin, :stars, :credits, :school_name, :stars_redeemed,
                  :limbo_credits, :last_download_email, :downloads_since_email
  
  has_many :uploads, :dependent => :destroy
  belongs_to :school
  has_many :downloads, :source => :user_id, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  has_many :purchases
  
  has_many :responses, :dependent => :destroy 
  has_many :requests, :dependent => :destroy
  
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  validates :email, :presence => true, :uniqueness => { :case_sensitive => false}
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false}
  validates :school_id, :presence => { :message => "must be in our database, pick a school from the suggestions as you type"}
  #WARNING
  #THIS SHOULD REALLY BE BEFORE_SAVE
  before_create :encrypt_password
  
  #NECESSARY DUE TO POSTGRE
  after_create :set_defaults, :reset_downloads
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_pepper(id, cookie_pepper)
    user = find_by_id(id)
    return nil  if user.nil?
    return user if user.pepper == cookie_pepper
  end
  
  def confirm
    self.confirmed = true
    self.save(:validate => false)
  end
  
  #getter for school name
  def school_name
    school.name if school
  end
  
  #setter for school name (will create school if it didn't find one)
  def school_name=(name)
    self.school = School.find_by_name(name) unless name.blank?
  end
  
  def add_credits(num)
    self.credits += num
  end
  
  def get_stars(num)
    self.stars += num
    if self.stars >= 10
      self.stars_redeemed += 10
      self.stars -= 10
      self.credits += 1
    end
    self.save(:validate => false)
  end
  
  #WARNING 
  #THIS ALLOWS FOR NEGATIVE CREDITS
  def charge
    self.credits -= 1
    self.save(:validate => false)
  end
  
  def has_downloaded?(file)
    @downloads = self.downloads.find(:all, :conditions => "upload_id = #{file.id}")
    return (@downloads.length > 0)
  end
  
  def has_responded?(request)
    @responses = self.responses.find(:all, :conditions => "request_id = #{request.id}")
    return (@responses.length > 0)
  end
  
  def has_commented?(upload)
    @comments = upload.comments.find(:all, :conditions => {:user_id => self.id}) unless upload.nil?
    return (@comments.length > 0)
  end
  
  def make_request
    if self.limbo_credits.nil?
      self.limbo_credits = 0
    end
    self.limbo_credits += 2
    self.credits -= 2
    self.save(:validate => false)
  end
  
  def return_deposit
    self.limbo_credits -=2
    self.credits +=2
    self.save(:validate => false)
  end
  
  def response_accepted
    self.credits += 2
    self.save(:validate => false)
  end
  
  def add_swag(num)
    old_swag_div = (self.swag / 5000)
    new_swag_div = ((self.swag + num) / 5000)
    
    #this is if you've crossed a new 5000 SWAG mark
    if (new_swag_div > old_swag_div)
      self.credits += 2
    end
    
    self.swag += num
    self.save(:validate => false)
  end
  
  def add_download
    self.downloads_since_email += 1
    self.save(:validate => false)
  end
  
  def reset_downloads
    self.last_download_email = DateTime.now
    self.downloads_since_email = 0
    self.save(:validate => false)
  end
  
  def set_defaults
    stars_redeemed = 0
    swag = 100
    last_download_email = (DateTime.now - 1.days)
    downloads_since_email = 0
    self.save(:validate => false)
  end
    

  private
  
    def encrypt_password
      self.pepper = make_pepper unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{pepper}--#{string}")
    end
    
    def make_pepper
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  
  def new
    if signed_in?
      flash[:notice] = "You already have a StudyHeist account"
      redirect_to current_user
    else   
      @user = User.new
    end
  end
  
  def create
      @user = User.new(params[:user])
      if @user.save
        flash[:notice] = "Welcome to StudyHeist!  
                          Before you can log in, 
                          you must click the confirmation link in 
                          your email inbox."

        #Auto-confirm users in development                  
        if ENV['RAILS_ENV'] == "development"
          @user.confirm
        end
        
        UserMailer.welcome_email(@user).deliver
        
        redirect_to root_path
      else
        flash.now[:error] = "Sorry, there was an error creating your account"
        render 'new'
      end
  end
  
  def show
    @user = User.find(params[:id])
    @uploads = @user.uploads.all
    @downloads = @user.downloads.all
    @requests = @user.requests.all
    if params[:token]
      if params[:token] == secure_hash(@user.username)
        flash[:success] = "Account Confirmed. Please sign in to continue"
        redirect_to signin_path
        @user.confirm
      else
        flash[:error] = "An error occurred during account confirmation."
        redirect_to root_path
      end
    else
      if !signed_in?
        flash[:notice] = "You need to sign in to do that"
        redirect_to signin_path
      end
    end
    
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :action => "edit"
    end
  end
  
  def add
    @user = User.find(params[:id])
    @user.add_credits(5)
    if @user.save(:validate => false)
      flash[:success] = "Five more credits added!"
    else
      flash[:error] = "Sorry, buying credits failed"
    end
    redirect_to root_path
  end
  
  #======================================================
  private
  #======================================================


      def correct_user
          user = User.find(params[:id])
          right_user = (current_user.id == user.id) unless current_user.nil?
          if (right_user == false)
            flash[:error] = "Sorry, you don't have permission to do that"
          end
          redirect_to(root_path) unless (right_user == true)
      end
      
      def admin_user
          redirect_to(root_path) unless current_user.admin?
      end
  
end

app/views/users/_form.html.erb
<script>
$(document).ready(function () {
  	auto_school('#user_school_name');
});
</script>

<%= form_for(@user, :html => { "data-validate" => "parsley"}) do |f| %>
	<%= f.error_messages %>
	<div class = "field" >
		<%= f.label :Username, "Username*" %>
		<%= f.text_field :username,
			"data-trigger" => "change",
			"data-notblank" => "true",
			"data-type" => "alphanum" %>
	</div>
	<div class = "field" >
		<%= f.label :Email, "Email Address*" %>
		<%= f.text_field :email,
			"data-trigger" => "change",
			"data-notblank" => "true",
			"data-type" => "email" %>
	</div>
	<div class = "field" >
		<%= f.label :Password, "Password*" %>
		<%= f.password_field :password,
			"data-trigger" => "change",
			"data-notblank" => "true",
			"data-validation-minlength" => "1", 
			"data-minlength" => "6", 
			"data-maxlength" => "40" %>
	</div>
	<div class = "field" >
		<%= f.label :Password_Confirmation, "Confirm Password*" %>
		<%= f.password_field :password_confirmation,
			"data-trigger" => "change",
			"data-equalTo" => "#user_password" %>
	</div>
	<div class = "field" >
		<%= f.label :school_name, "School Name*" %>
		<%= f.text_field :school_name,
			"data-trigger" => "change",
			"data-notblank" => "true" %>
	</div>
	<div class = "field" >
		<%= f.label :Graduation, "Year of Graduation*" %>
		<%= f.text_field :graduation,
			"data-trigger" => "change",
			"data-type" => "digits",
			"data-minlength" => "4",
			"data-maxlength" => "4" %>
	</div>

	<%= f.hidden_field(:credits, :value => '5' )%>
	<%= f.hidden_field(:stars, :value => '0' )%>
	<%= f.hidden_field(:numfiles, :value => '0' )%>
	<%= f.hidden_field(:admin, :value => 'false' )%>
	<%= f.hidden_field(:confirmed, :value => 'false' )%>
	<%= f.hidden_field(:limbo_credits, :value => '0' )%>
	
  	<div class="actions">
    	<%= f.submit "Submit", :class => "btn btn-success" %>
  	</div>
<% end %>

<p><b>Note:</b> * indicates required field </p>

app/views/users/edit.html.erb
<h2>Edit User</h2>
<%= render 'form'%>

app/views/users/new.html.erb
<h2>Sign Up!</h2>
</br>

<%= render 'form' %>

<p>
<b>Note: </b>
by creating a StudyHeist account you agree to the <%= link_to "Terms of Service", terms_path %>
</p>

app/views/users/show.html.erb
<div class = "alert" id = "#flash">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
Want to earn 2 free credits for uploading a file?  Need to request a file you don't see here?  Try visiting the <%= link_to "#{current_user.school.name} Marketplace!", school_requests_path(current_user.school)%>
</div>

<div class="page-header">
  <h1>
  	<%= @user.username %> 
  	<small>
  		(
  		<% if @user == current_user %>
  			<%= @user.credits %> Credits, 
  		<% end %>
  		<%= @user.swag %> SWAG
  		)
  	</small>
  </h1>
	<% if signed_in? %>
		<% if @user == current_user %>
			<%= render 'shared/stripe_form' %>
		<% end %>
	<% end %>
</div> 

<h3>
	User Info
	<% if signed_in? %>
		<% if @user == current_user %>
			<small>
				<%= link_to "Edit Your Profile" ,edit_user_path(@user) %>
			</small>
		<% end %>
	<% end %>
</h3>
<div class="well">
	<p>
		<h4>
			School: 
			<% if @user.school %>
				<%= link_to @user.school.name, 
							@user.school,
							:class => "a-dot" %>
			<% elsif @user == current_user %>
				School not in our database, you won't be able to upload until you select a valid school.
			<% else %>
				None
			<% end %>
		</h4>
		<h4>
			Graduation Year: 
			<span>
				<%= @user.graduation %>
			</span>
		</h4>
		<h4>
			Credits Earned: 
			<span>
				<%= @user.stars_redeemed/10 %>
			</span>
		</h4>
	</p>
</div>

<h3>Uploads</h3>
<%= render "uploads/uploads", :uploads => @uploads, :downloads => false %>

<% if signed_in? %>
	<% if @user == current_user %>
		<h3>Downloads</h3>
		<%= render 	"uploads/uploads", :uploads => @downloads, :downloads => true %>
		<br>
		<br>

		<h3>Requests</h3>
		<div>
			<% if @requests.size == 0 %>
				No requests
			<% else %>
				<%= render  "requests/requests", :requests => @requests %>
			<% end %>
		</div>
	<% end %>
<% end %>