config/routes.rb
 Studyvault::Application.routes.draw do
  
  root :to => "pages#index"
  
  resources :users do
    get 'add', :on => :member
  end
  
  resources :uploads, :only =>[:create, :destroy, :show]
  
  resources :uploads do
    get 'download', :on => :member
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :schools do
    resources :requests
  end
  
  resources :courses
  resources :comments
  
  resources :downloads
  
  resources :purchases
  
  resources :requests do
    resources :responses
  end
  
  resources :responses do
    get 'download', :on => :member
    get 'accept', :on => :member
  end
  
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'
  match '/about',     :to => 'pages#about'
  match '/aboutswag', :to => 'pages#aboutswag'
  match '/terms',     :to => 'pages#terms'
  match '/upload',    :to => 'pages#upload'
  match '/search',     :to => 'pages#search'
  
  match '/schoolsearch', :to => 'schools#search'
  match '/coursesearch', :to => 'courses#search'
  match '/professors',   :to => 'pages#professors'
  

end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment, :html => {:multipart => true}) do |f| %>
	<div class = "field">
		<%= f.label(:rating, "Rating (out of 10)") %>
		<%= f.select(:rating, options_for_select([["0",0],["1",1],["2",2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9],["10",10]])) %>
	</div>
	<div class = "field">
		<%= f.label(:content, "Your Comments") %>
		<%= f.text_area :content, :class => "round", :style => "max-height:100px;" %>
	</div>
	<%= f.hidden_field(:file_id, :value => @upload.id )%>
	<div class="actions" id = "spintarget">
    	<%= f.submit "Submit", :class => "btn btn-success" %>
  	</div>
<% end %>

app/views/shared/_header.html.erb
 <div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn-navbar" data-toggle="collapse" data-target=".nav-collapse" style="margin-top:8px;" >
        <i class="icon-bar"></i>
        <i class="icon-bar"></i>
        <i class="icon-bar"></i>
      </a>
      <div class="logo" id="logo">
        <a class="brand" href="/">StudyHeist</a>
      </div>
      <!-- <div class="nav-collapse collapse"> -->
        <ul class="nav">
          <% if signed_in? %>
            <li><%= link_to "#{current_user.username} (#{current_user.credits} CR) ", current_user %></li>
            <li><%= link_to "Upload", "/upload" %></li>
            <li><%= link_to "Search", "/search" %></li> 
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Search", "/search" %></li> 
            <li><%= link_to "Sign In", signin_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>
        </ul>
      <!-- </div> --><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_oldheader.html.erb
	<div id = "header">
		<a href= <%= "#{root_path}" %>> <img alt = "StudyHeist" src = "/images/logo.png" class = "logo" ></img></a>
		
		<div class = "usertop">
		<% if signed_in? %>
			<%= link_to "#{current_user.username} (#{current_user.credits} CR | #{current_user.swag} SWAG ) ", current_user %> | 
			<%= link_to "About", about_path %> |
			<%= link_to "Sign Out", signout_path %>
		<% else %>
			<%= link_to "About ", about_path %> |
			<%= link_to "Sign In", signin_path %> |
			<%= link_to "Sign Up", signup_path %>
		<% end %>
		</br>
		<div class="fb-like" data-href="http://www.facebook.com/pages/StudyHeist/227560507320555" data-send="false" data-layout="button_count" data-width="80" data-show-faces="false" data-colorscheme="light" data-font="arial">
		</div>
		<% if @swag %>
			<% if @swag > 0 %>
			<div id = "swagbox" class = "roundish">
				You earned <%= @swag %> SWAG!
			</div>
			<% elsif @swag < 0 %>
			<div id = "swagbox" class = "roundish">
				You lost <%= @swag %> SWAG.
			</div>
			<% end %>
		<% end %>	
		</div>
		
		
		</br>
		
		<% [:info, :error, :notice, :alert, :success].each do |key| %>
   		<% if flash[key] %>
   		<p>
		<div class="<%= key %>" id="flash">
     		<span><%= flash[key] %></span>
   		</div>
		</p>
   		<% end %>
 		<% end %>

	</div>

app/views/shared/_search_form.html.erb
<div class="row">
	<%= form_tag do %>
		<div class="span3">
			<%= label_tag(:school, "School: ")  %>
			<%= text_field_tag :school, nil, :id => 'school', :class => "search-query", :value => @school_placeholder %>
		</div>
		<% if signed_in? %>
			<!--<div class="span4">
				
				<table style="margin:0 auto;padding0;">
					<tr>
						<td style="padding:0;">
							<%= label_tag(:subject, "Subject: ") %>
						</td>
						<td style="padding:0;">
							<%= label_tag(:course_code, "Course: ")  %>
						</td>
					</tr>
					<tr>
						<td>
							<%= text_field_tag :subject, nil, 
								:id => 'subject', 
								:class => "search-query input-small", 
								:value => @subject,
								:placeholder => "ex: CHEM"  %>
						</td>
						<td>
							<%= text_field_tag :course_code, nil, 
								:id => 'course_code', 
								:class => "search-query input-small", 
								:value => @course_code,
								:placeholder => "ex: 101"  %>
						</td>
					</tr>
				</table>
				-->
			<div class="span3" >
				<%= label_tag(:course_name, "Course: ") %>
				<%= text_field_tag :course_name, nil, :id => 'course', :class => "search-query", :value => @course_name,
					:placeholder => "ex: CIS 101" %>
			</div>
			<div class="span3">
				<%= label_tag(:professor, "Professor: ") %>
				<%= text_field_tag :professor, nil, :id => 'professor', :class => "search-query", :value => @professor_name,
					:placeholder => "ex: Mandelbrot" %>
			</div>
			<div class="span2">
				<table>
					<tr class="pad">
						<td>Any</td>
						<td>All</td>
					</tr>
					<tr class="pad">
						<td>
							<input type="radio" value="ANY" name="match" />
						</td>
						<td>
							<input type="radio" value="ALL" name="match" checked="checked" />
						</td>
					</tr>
				</table>
			</div>
		<% else %>
			<div class="span3">
				<label for="fakecourse">Course: </label>
				<input type="text" disabled="disabled" name="fakecourse" class="search-query" value="Sign in to search by Course.">
			</div>
			<div class="span3">
				<label for="fakeprof">Professor: </label>
				<input type="text" disabled="disabled" name="fakeprof" class="search-query" value="Sign in to search by Professor.">
			</div>
		<% end %>
		<div class="span1">
			<%= label_tag(:search, "Search:", :class => "white") %>
			<%= submit_tag "Search", :class => "btn btn-success", :style => "float:left;" %>
		</div>
	<% end %>
</div>

app/views/shared/_stripe_form.html.erb
<script src="https://checkout.stripe.com/v2/checkout.js"></script>

<input type="submit" class="btn btn-success" id="stripeButton" value="Buy Credits &raquo;"></input>

<%= form_tag purchases_path do %>
	<input type="hidden" name="stripeToken" id="stripeToken"></input> 
<% end %>

app/views/shared/_upload_form.html.erb
<script>
$(document).ready(function () {
	//Auto complete
	auto_course('#upload_temp_coursename');
	auto_professor('#upload_professor');
 	
 	//Loading spinner
 	$('.btn-success').live('click',function(e){
 		if ($(this).hasClass("disabled") == false) {
 			loading_state('.btn-success',"Uploading....");
 			setTimeout(function() {
 				$('form').submit();
 			},
 			200);
 			return false;
 		}
 	});

 	//$('#upload_temp_coursename').change(function(e) {
 		//$('#coursename_suggest').text("Did you mean?");
 	//});

});
</script>

<%= form_for(@upload, :html => {:multipart => true, "data-validate" => "parsley"}) do |f| %>
	
	<%= f.error_messages %>
	<div class="row">
		<div class = "field span4">
			<%= f.label(:semester, "Semester*") %>
			<%= f.select(:semester, options_for_select([["Fall","Fall"],["Spring","Spring"],["Summer","Summer"],["Winter","Winter"]])) %>
		</div>
		<div class = "field span4">
			<%= f.label(:year, "Year*") %>
			<%= date_select :upload, :year, :start_year => 1980, :end_year => Time.now.year, :discard_month => true %>
		</div>
	</div>
	<div class="row">
		<!--
		<div class = "field span4">
			<%= f.label(:temp_coursename, "Course Name* (ex: BIOL 202)") %>
			<%= f.text_field :temp_coursename,
				"data-validation-minlength" => "2",
				"data-trigger" => "change",
				"data-notblank" => "true" %>
		</div>
		-->
		<div class = "field span4">
			<table>
				<tr>
					<td>
						<%= f.label(:subject, "Subject*") %>
					</td>
					<td>
						<%= f.label(:course_code, "Course Code*") %>
					</td>
				</tr>
				<tr>
					<td>
						<% if @subjects.length > 5 %>
							<%= collection_select(:upload, :subject, 
											@subjects, :name, :name,
											{}, 
											{:style => "width:90px;"}) %>
						<% else %>
							<%= f.text_field :subject,
								:class => "input-small",
								:style => "display:inline-block;",
								:placeholder => "ex: CHEM",
								"data-validation-minlength" => "1",
								"data-trigger" => "change",
								"data-notblank" => "true" %>
						<% end %>
					</td>
					<td>
						<%= f.text_field :course_code,
							:class => "input-small",
							:style => "display:inline-block;",
							:placeholder => "ex: 101",
							"data-validate-minlength" => "1",
							"data-trigger" => "change",
							"data-notblank" => "true" %>
					</td>
				</tr>
			</table>
		</div>

		<div class = "field span4">
			<%= f.label(:professor, "Professor*") %>
			<%= f.text_field :professor,
				"data-validation-minlength" => "2",
				"data-trigger" => "change",
				"data-notblank" => "true" %>
		</div>
	</div>

	<div class="row">
		<div class = "field span8">
			<%= f.label(:description, "File Description") %>
			<%= f.text_field :description, :class => "description input-large" %>
		</div>
	</div>
	
	<%= f.hidden_field(:stars, :value => '0' )%>
	<%= f.hidden_field(:ratings, :value => '0' )%>
	<%= f.hidden_field(:school_id, :value => current_user.school.id )%>
	
	<div class = "field upload">
		<div class = "uploadbutton">
			<%= f.file_field(:linked) %>
		</div>
	</div>
	
	<br />

	<div class="actions" id = "spintarget">
    	<%= f.submit "Upload File", :class => "btn btn-success" %>
  	</div>
	
<% end %>
<p><b>Note:</b> * indicates required field </p>